name: ATM651
channels:
  - conda-forge
  - defaults
dependencies:
   - python=3
   - numpy
   - matplotlib
   - cartopy
   - jupyter
   - rise
   - netcdf4
   - owslib
   - metpy
   - pint
   - siphon
   - xarray
   - fastparquet
   - psutil
   - fsspec
   - pip
   - ffmpeg
   - pip:
     - ipyidv
     - mseplots-pkg
